using MauiTouchEffect.Platforms.Android;

namespace MauiTouchEffect;

public static class AppBuilderExtentions
{
    /// <summary>
	/// Initializes the .NET MAUI touch effects
	/// </summary>
	/// <param name="builder"><see cref="MauiAppBuilder"/> generated by <see cref="MauiApp"/> </param>
	/// <returns><see cref="MauiAppBuilder"/> initialized for <see cref="MauiTouchEffect"/></returns>
	public static MauiAppBuilder UseMauiTouchEffect(this MauiAppBuilder builder)
    {
		builder.ConfigureEffects(effects =>
		{
#if __ANDROID__
                effects.Add<TouchEffect, PlatformTouchEffect>();
#endif
		});
        return builder;
    }
}
